# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wtlee\Desktop\HW3\107522010_HW3\ui\Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(680, 570, 71, 41))
        self.load.setObjectName("load")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(210, 600, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.learn = QtWidgets.QLineEdit(self.centralwidget)
        self.learn.setGeometry(QtCore.QRect(140, 600, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.learn.setFont(font)
        self.learn.setObjectName("learn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 600, 111, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.menu = QtWidgets.QComboBox(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(500, 570, 161, 31))
        self.menu.setMaxCount(2147483644)
        self.menu.setObjectName("menu")
        self.menu.addItem("")
        self.menu.addItem("")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 351, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ltest = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ltest.setContentsMargins(0, 0, 0, 0)
        self.ltest.setObjectName("ltest")
        self.clear_layout = QtWidgets.QPushButton(self.centralwidget)
        self.clear_layout.setGeometry(QtCore.QRect(290, 600, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.clear_layout.setFont(font)
        self.clear_layout.setObjectName("clear_layout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(430, 20, 371, 531))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.test = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.test.setContentsMargins(0, 0, 0, 0)
        self.test.setObjectName("test")
        self.menu_2 = QtWidgets.QComboBox(self.centralwidget)
        self.menu_2.setGeometry(QtCore.QRect(20, 560, 181, 31))
        self.menu_2.setMaxCount(2147483644)
        self.menu_2.setObjectName("menu_2")
        self.menu_2.addItem("")
        self.menu_2.addItem("")
        self.all = QtWidgets.QCheckBox(self.centralwidget)
        self.all.setGeometry(QtCore.QRect(220, 560, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(14)
        self.all.setFont(font)
        self.all.setObjectName("all")
        self.one = QtWidgets.QCheckBox(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(290, 560, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(14)
        self.one.setFont(font)
        self.one.setObjectName("one")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load.setText(_translate("MainWindow", "load"))
        self.start.setText(_translate("MainWindow", "start"))
        self.lineEdit.setText(_translate("MainWindow", "循環次數"))
        self.menu.setItemText(0, _translate("MainWindow", "Basic_Training.txt"))
        self.menu.setItemText(1, _translate("MainWindow", "Bonus_Training.txt"))
        self.clear_layout.setText(_translate("MainWindow", "clear"))
        self.menu_2.setItemText(0, _translate("MainWindow", "Basic_Testing.txt"))
        self.menu_2.setItemText(1, _translate("MainWindow", "Bonus_Testing.txt"))
        self.all.setText(_translate("MainWindow", "all"))
        self.one.setText(_translate("MainWindow", "one"))

